// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/24/2026, 10:30:38 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/peterayenoto/netpoc/analytics/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/plugins/**/*.{js,ts,mjs}","/Users/peterayenoto/netpoc/analytics/composables/**/*.{js,ts,mjs}","/Users/peterayenoto/netpoc/analytics/utils/**/*.{js,ts,mjs}","/Users/peterayenoto/netpoc/analytics/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/peterayenoto/netpoc/analytics/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;